<?php

define('BASE_PATH', __DIR__);
define('CONFIG_PATH',  BASE_PATH.DIRECTORY_SEPARATOR.'config');
define('APP_PATH', BASE_PATH.DIRECTORY_SEPARATOR.'app');
define('PUBLIC_PATH', BASE_PATH.DIRECTORY_SEPARATOR.'httpdocs');
define('RESOURCE_PATH', BASE_PATH.DIRECTORY_SEPARATOR.'resources');
define('VIEW_PATH', RESOURCE_PATH.DIRECTORY_SEPARATOR.'views');
define('LOG_PATH', BASE_PATH.DIRECTORY_SEPARATOR.'logs');
define('UTILS_PATH', BASE_PATH.DIRECTORY_SEPARATOR.'utilities');